
TYPE
	COB_ID120 : 	STRUCT 
		bBereit : BOOL;
		bContainerUeberBeladetrichter : BOOL;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		bPostennummer : BOOL;
		udPostennummer : UDINT;
		usFehlernummer : USINT;
		bAuftragskennzeichen : BOOL;
		szAuftragskennzeichen : STRING[12];
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bNotAusHF : BOOL;
		bDatenuebernahmeLift : BOOL;
		bSchiebeVorposition : BOOL;
		usEinlaufInSpeibahnNr : USINT;
		usAuslaufAusSpeibahnNr : USINT;
		usReserve1 : USINT;
		usReserve2 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID121 : 	STRUCT 
		bBereit : BOOL;
		bSackOeffnen : BOOL;
		bSackLeerWeiter : BOOL;
		bFreigLiftBeschickungSpeibahn : BOOL;
		bNotAusPT : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		usReserve6 : USINT;
		usReserve7 : USINT;
		bSchiebesignalPT : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID122 : 	STRUCT 
		bBereit : BOOL;
		bProgKat : BOOL;
		uiProgKat : UINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bPostennummer : BOOL;
		udPostennummer : UDINT;
		bAuftrKennz : BOOL;
		szAuftragskennzeichen : STRING[12];
		bPostenAufBelband : BOOL;
		bPostendatenGueltig : BOOL;
		bNotAusSackbeladung : BOOL;
		usFehlerNr : USINT;
		usZaehler : USINT;
		usReserve1 : USINT;
		usReserve2 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID123 : 	STRUCT 
		bBereit : BOOL;
		bDatenBereitstellen : BOOL;
		bBeladesignal : BOOL;
		bNotAusPT : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		usReserve6 : USINT;
		usReserve7 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID201 : 	STRUCT 
		bBereit : BOOL;
		bVorsignal : BOOL;
		bEntladesignal : BOOL;
		bKeineRueckgewinnung : BOOL;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bNotAusWM : BOOL;
		bFreigabeDesinfektion : BOOL;
		bTankIstLeer : BOOL;
		bFreigabeSpuelen : BOOL;
		bEndeDesinfektion : BOOL;
		usReserve1 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID209 : 	STRUCT 
		bBereit : BOOL;
		bVorsignal : BOOL;
		bEntladesignal : BOOL;
		bKeineRueckgewinnung : BOOL;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bNotAusWetShuttle : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID211 : 	STRUCT 
		bBereit : BOOL;
		bBeladebereit : BOOL;
		bSchiebeimpSpbPreXOR_WETShuttle : BOOL;
		bSchiebeimpulsErsteEntwaess : BOOL;
		bSchiebeimpulsZweiteEntwaess : BOOL;
		bAblassvZwangsoeffnErsteEnt : BOOL;
		bAblassvZwangsoeffnZweiteEnt : BOOL;
		bFehlerBelgewErtsteEntwaess : BOOL;
		bFehlerBelgewZweiteEntwaess : BOOL;
		usFehlerErsteEntwaess : USINT;
		usFehlerZweiteEntwaess : USINT;
		usFehlerWetShuttle : USINT;
		bNotAusEntwaessWetShuttle : BOOL;
		bStartDesinfektion : BOOL;
		bStartSpuelen : BOOL;
		bEndeSpuelen : BOOL;
		bReserve1 : BOOL;
		bReserve2 : BOOL;
		bReserve3 : BOOL;
		bReserve4 : BOOL;
		bReserve5 : BOOL;
		bReserve6 : BOOL;
		bReserve7 : BOOL;
		bReserve8 : BOOL;
		bReserve9 : BOOL;
		bReserve10 : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bSicherheitstuerPTPP : BOOL;
		bStartbefehlAnPT : BOOL;
	END_STRUCT;
	COB_ID219 : 	STRUCT 
		bBereitEntwWetShuttle : BOOL;
		bBereitEntw : BOOL;
		bBeladebereit : BOOL;
		bSchiebeimpuls : BOOL;
		bHANDWetShuttleEntladen : BOOL;
		bFehlerBeladegewicht : BOOL;
		usFehlerEntw : USINT;
		usFehlerWetShuttle : USINT;
		bNotAusEntw : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		usReserve6 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID221 : 	STRUCT 
		bBereit : BOOL;
		bPostendatenGueltig : BOOL;
		bUnglPostenKeineDPBelAmTrockner : BOOL;
		bTrocknerprogOderKategorie : BOOL;
		uiTrocknerprogKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bNotAusWM : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID231 : 	STRUCT 
		bBereit : BOOL;
		usBeladungTrockner : USINT;
		usEntladungTrockner : USINT;
		usTransferZBvorTrockner : USINT;
		usTransferZBvorHFB : USINT;
		usFehlernummer : USINT;
		bNotAusVerbundEinzeltr : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID251_253_255_257 : 	STRUCT 
		bBereit : BOOL;
		bNotAusVerbund : BOOL;
		bProgKat : BOOL;
		uiProgKat : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		usZiel : USINT;
		bBeladeende : BOOL;
		usReserve1 : USINT;
		bSperreBereich : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bBeladestart : BOOL;
	END_STRUCT;
	COB_ID252_254_256_258 : 	STRUCT 
		bBereit : BOOL;
		bNotAusSackbeladung : BOOL;
		bSackBereit : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		usReserve6 : USINT;
		usReserve7 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bSperreBereich : BOOL;
	END_STRUCT;
	COB_ID261 : 	STRUCT 
		bBereit : BOOL;
		bBeladungBeendet : BOOL;
		bBeladungAktiv : BOOL;
		bSaugboxBelegt : BOOL;
		bNotHaltSaugbox : BOOL;
		uiMeldung : UINT;
		uiGewicht : UINT;
	END_STRUCT;
	COB_ID262 : 	STRUCT 
		bBereit : BOOL;
		bSackBereit : BOOL;
		bEntladefreigabe : BOOL;
		bNotHaltSackspeicher : BOOL;
	END_STRUCT;
	COB_ID301bis304 : 	STRUCT 
		bBereit : BOOL;
		bEntwaesserungEntlaedt : BOOL;
		bPostenInEntwaesserung : BOOL;
		bEntladestoerungAnPresse : BOOL;
		bSperreFahrbandVonZentrifuge : BOOL;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bBandlaufEntladeband : BOOL;
		bVorsignalEntladung : BOOL;
		bNotAusEntwaesserung : BOOL;
		usReserve1 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bLichtschrankeBandende : BOOL;
		bEntladeueberwachung : BOOL;
	END_STRUCT;
	COB_ID306 : 	STRUCT 
		bBereit : BOOL;
		bAeroEntlaedt : BOOL;
		bPostenInAero : BOOL;
		bSperreFahrbandVonAero : BOOL;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bNotAusAero : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bUebergabestoerung : BOOL;
	END_STRUCT;
	COB_ID110 : 	STRUCT 
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiProgrammKategorie : UINT;
		uiGewicht : UINT;
		bBereit : BOOL;
		bEntladesignal : BOOL;
		bEntladebereit : BOOL;
		bUebergabestoerung : BOOL;
		bNotAusEntsander : BOOL;
		bProgrammOderKategorie : BOOL;
		Alignm1 : USINT;
		Alignm2 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID111 : 	STRUCT 
		bBereit : BOOL;
		bEntladefreigabe : BOOL;
		bUebernahmestoerung : BOOL;
		bNotAusBeladeband : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID307 : 	STRUCT 
		bBereit : BOOL;
		bEntladesignal : BOOL;
		bPostenAufBand : BOOL;
		bEntladestoerungBand : BOOL;
		bKundenwechsel : BOOL;
		bBandlaufEntladeband : BOOL;
		bProgrammKategorie : BOOL;
		bNotAusVerbund : BOOL;
		udPostennummer : UDINT;
		uiGewicht : UINT;
		uiProgrammKategorie : UINT;
		udKundennummer : UDINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID311bis314 : 	STRUCT 
		bBereit : BOOL;
		bBeladebereit : BOOL;
		bUebernahmestoerungVerbETAero : BOOL;
		bEntladelichtschrZentrifuge : BOOL;
		bNotAusETVerbAero : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		usReserve6 : USINT;
		usReserve7 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bSchutzgitterOffen : BOOL;
		bStartPresse : BOOL;
	END_STRUCT;
	COB_ID316 : 	STRUCT 
		bBereit : BOOL;
		bBeladebereit : BOOL;
		bUebernahmestoerungVerbET : BOOL;
		bNotAusVerbET : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		usReserve6 : USINT;
		usReserve7 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID317 : 	STRUCT 
		bBereit : BOOL;
		bBeladebereit : BOOL;
		bBeladeunterbrechung : BOOL;
		bUebernahmestoerung : BOOL;
		bQuittierungKundenwechsel : BOOL;
		bNotAusAero : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID351bis354 : 	STRUCT 
		bBereit : BOOL;
		bAktPosFehler : BOOL;
		bAktPosWarnung : BOOL;
		bAktPosGesperrt : BOOL;
		usAktPos : USINT;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		usReserve1 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bIdxPostenspeicher_1 : BOOL;
		bIdxPostenspeicher_2 : BOOL;
		bIdxPostenspeicher_4 : BOOL;
		bNotAusAero : BOOL;
	END_STRUCT;
	COB_ID361bis369 : 	STRUCT 
		usStation : USINT;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		usReserve1 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bBereit : BOOL;
	END_STRUCT;
	COB_ID371bis379 : 	STRUCT 
		bDruckstatus : BOOL;
		usDruckerfehler : USINT;
		usStation : USINT;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
		bBereit : BOOL;
	END_STRUCT;
	COB_ID401bis419 : 	STRUCT 
		bBereit : BOOL;
		bBeladeanforderung : BOOL;
		bEntladefreigabe : BOOL;
		bAnsteuerungSpeicherband : BOOL;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bNotAusVerbST : BOOL;
		bVorsignal : BOOL;
		bKippsperre : BOOL;
		usReserve1 : USINT;
		usReserve2 : USINT;
		bFreigabeFlusen : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID421bis439 : 	STRUCT 
		bBereit : BOOL;
		bBeladebereit : BOOL;
		bBelaedt : BOOL;
		bEntladebereit : BOOL;
		bEntlade : BOOL;
		bTrocknet : BOOL;
		bHauptgeblaese : BOOL;
		bFlusenabsaugung : BOOL;
		bAbkuehlung : BOOL;
		bLichtschrSpeicherbandHinten : BOOL;
		bLichtschrSpeicherbandVorne : BOOL;
		bTemperatureinheit : BOOL;
		uiAbluftTemp : UINT;
		bEIN : BOOL;
		bStoerung : BOOL;
		uiRestzeit : UINT;
		bProgrammOderKategorie : BOOL;
		uiProgrammKategorie : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		bNotAusTrockner : BOOL;
		bHand : BOOL;
		uiIRTemp : UINT;
		usReserve1 : USINT;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID441bis459 : 	STRUCT 
		uiTrocknerrestzeit : UINT;
		usReserve1 : USINT;
		usReserve2 : USINT;
		usReserve3 : USINT;
		usReserve4 : USINT;
		usReserve5 : USINT;
		bVorsignalFlusen : BOOL;
		bSaugbeladungAktiv : BOOL;
		bAnforderungFlusen : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID480 : 	STRUCT 
		bBereit : BOOL;
		bNotAusAero : BOOL;
		bBeladebereit : BOOL;
		bBeladungAktiv : BOOL;
		bStoerung : BOOL;
		bBeladeanfHalbauto : BOOL;
		bBeladepause : BOOL;
		bBeladeabbruch : BOOL;
		bFreigabeBeladung : BOOL;
		bDurchschleusenStart : BOOL;
		bProgKat : BOOL;
		uiProgKat : UINT;
		udPostennummer : UDINT;
		udKundennummer : UDINT;
		uiGewicht : UINT;
		usReserve1 : USINT;
		bReserve1 : BOOL;
		bReserve2 : BOOL;
		bReserve3 : BOOL;
		bReserve4 : BOOL;
		bReserve5 : BOOL;
		bReserve6 : BOOL;
		bReserve7 : BOOL;
		bReserve8 : BOOL;
		bReserve9 : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	COB_ID481 : 	STRUCT 
		bBereit : BOOL;
		bNotAusAnlagenStrg : BOOL;
		bBeladeanfAuto : BOOL;
		bStoerung : BOOL;
		bAnlagenstrgHalbauto : BOOL;
		bAnlagenstrgAuto : BOOL;
		bPauseAktiv : BOOL;
		bDurchschleusen : BOOL;
		bFreigabeDurchschl : BOOL;
		bProgKat : BOOL;
		uiProgKat : UINT;
		uiGewicht : UINT;
		udKundennummer : UDINT;
		udPostennummer : UDINT;
		usReserve1 : USINT;
		bReserve1 : BOOL;
		bReserve2 : BOOL;
		bReserve3 : BOOL;
		bReserve4 : BOOL;
		bReserve5 : BOOL;
		bReserve6 : BOOL;
		bReserve7 : BOOL;
		bReserve8 : BOOL;
		bReserve9 : BOOL;
		bReserve10 : BOOL;
		a_usCustomize : ARRAY[0..6] OF USINT;
	END_STRUCT;
	InitCAN2PV : 	STRUCT 
		pPVData : UDINT;
		uiCANID : UINT;
		usCommDirection : USINT;
		pEvVar : UDINT;
		iMode : INT;
	END_STRUCT;
	_CAN1 : 	STRUCT 
		T_By0 : USINT;
		T_By1 : USINT;
		T_By2_By3 : UINT;
		T_By4_By5 : UINT;
		T_By6_By7 : UINT;
	END_STRUCT;
	_CAN2 : 	STRUCT 
		T1_By0 : USINT;
		T1_By1 : USINT;
		T1_By2_By3 : UINT;
		T1_By4_By5 : UINT;
		T1_By6_By7 : UINT;
		T2_By0 : USINT;
		T2_By1 : USINT;
		T2_By2_By3 : UINT;
		T2_By4_By5 : UINT;
		T2_By6_By7 : UINT;
		T3_By0 : USINT;
		T3_By1 : USINT;
		T3_By2_By3 : UINT;
		T3_By4_By5 : UINT;
		T3_By6_By7 : UINT;
		T4_By0 : USINT;
		T4_By1 : USINT;
		T4_By2_By3 : UINT;
		T4_By4_By5 : UINT;
		T4_By6_By7 : UINT;
		T5_By0 : USINT;
		T5_By1 : USINT;
		T5_By2_By3 : UINT;
		T5_By4_By5 : UINT;
		T5_By6_By7 : UINT;
	END_STRUCT;
	_CAN2Read : 	STRUCT 
		uiObjNr : UINT;
		ab_ByteArray : ARRAY[0..49] OF USINT;
		iNumberReceivedTels : INT;
		iNumberOfTels : INT;
	END_STRUCT;
	_CAN2Write : 	STRUCT 
		CAN2 : _CAN2;
		bBusy : BOOL;
		iNumberOfTels : INT;
		iTelsSent : INT;
		uiCOB_ident : UINT;
		tTimeLastTelSent : TIME;
	END_STRUCT;
	_CANAccess : 	STRUCT 
		CANMulQueue_q_ident : UDINT;
		CANMulOpen_us_ident : UDINT;
		CANopen_us_ident : UDINT;
	END_STRUCT;
	_DOAccess : 	STRUCT 
		DO_us_ident : UDINT;
	END_STRUCT;
	_InitCAN2PV : 	STRUCT 
		pPVData : UDINT;
		uiObjNr : UINT;
		usCommDirection : USINT;
		udCAN_q_ident : UDINT;
		pEvVar : UDINT;
		uiCOB_ident : UINT;
		bRunning : BOOL;
		iMode : INT;
	END_STRUCT;
	_InitCAN2Protocol : 	STRUCT 
		AccessInitDO : _DOAccess;
		CAN2DObCount : UINT;
		CANAccess : _CANAccess;
		DoAccessCAN2Write : _DOAccess;
		iMode : INT;
		DOAccessCAN2Read : _DOAccess;
	END_STRUCT;
END_TYPE
